### ISSUE TITLE
Error with 3.0.2: higher version than referenced assembly 'Microsoft.Testing.Platform'

### ISSUE THREAD

**Issue by WeihanLi** [Tyrrrz/GitHubActionsTestLogger#69]
### Version

3.0.2

### Platform

.NET 10 linux/windows/mac

### Steps to reproduce

see project here: https://github.com/WeihanLi/dotnet-httpie/actions/runs/23781691028/job/69295656131

got exception when update to 3.0.2

### Details

```
CSC : error CS1705: Assembly 'GitHubActionsTestLogger' with identity 'GitHubActionsTestLogger, Version=3.0.2.0, Culture=neutral, PublicKeyToken=f6822d7072e1e1b3' uses 'Microsoft.Testing.Platform, Version=2.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'Microsoft.Testing.Platform' with identity 'Microsoft.Testing.Platform, Version=2.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' [/home/runner/work/dotnet-httpie/dotnet-httpie/tests/HTTPie.IntegrationTest/HTTPie.IntegrationTest.csproj]
```

### Checklist

- [x] I have looked through existing issues to make sure that this bug has not been reported before
- [x] I have provided a descriptive title for this issue
- [x] I have made sure that this bug is reproducible on the latest version of the package
- [x] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by Tyrrrz** [comment]
Hmm.

Can you try installing the `Microsoft.Testing.Platform` package in its latest version explicitly?
